eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://api-service-registry.herokuapp.com/eureka
      non-secure-port: 80
      secure-port: 443
  instance:
    hostname: api-service-registry.herokuapp.com
    homePageUrl: https://${eureka.instance.hostName}/
    home-page-url-path: https://${eureka.instance.hostName}
 