eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://api-service-registry.herokuapp.com/eureka
      non-secure-port: 80
      
  instance:
    hostname: api-service-registry.herokuapp.com
    homePageUrl: https://${eureka.instance.hostName}/
    home-page-url-path: https://${eureka.instance.hostName}
    non-secure-port: 80