eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://api-service-registry.herokuapp.com/eureka
  instance:
    hostname: api-service-registry.herokuapp.com
